name: codingame-hs-skeleton
version: 1.1

dependencies:
- base
- aeson
- attoparsec
- bytestring
- codingame-hs
- directory
- filepath

executables:
  codingame-hs-skeleton-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -w
    - -O1
